"""
    file_renderer
    ~~~~~~~~~~~~~~~~~~~~~~~
    Houses the declaration of :py:class:`FileRenderer` along with
    supporting classes, functions, and attributes.
    ~~~~~~~~~~~~~~~~~~~~~~~
    Unpublished Copyright 2020 Andrew van Herick. All Rights Reserved.
"""

__author__ = 'Andrew van Herick'

import errno
import os
from abc import abstractmethod, ABC

from pyincept.architype_parameters import ArchitypeParameters


class FileRenderer(ABC):
    """
    This abstract base class determines the interfaces by which files built
    by this project should be rendered and saved.
    """

    def path(self, root_dir: str, params: ArchitypeParameters) -> str:
        """
        Returns the full path (possibly non-absolute) to the file that will
        be saved by :py:meth:`render_and_save`.

        :param root_dir: the root directory argument for
        :py:meth:`render_and_save`

        :param params: the parameters argument for :py:meth:`render_and_save`

        :return: the path
        """
        raise NotImplementedError()

    @abstractmethod
    def subpath(self, params: ArchitypeParameters) -> str:
        """
        Returns the subpath, under the root directory, of the file to be
        saved by :py:meth:`render_and_save`.

        :param params: the :py:`ArchitypeParameter`s to use as context when
        creating the subpath, e.g., when storing files whose sub-path might be
        determined by the package name.

        :return: the path
        """
        raise NotImplementedError()

    @abstractmethod
    def render(self, params: ArchitypeParameters) -> str:
        """
        Returns the content of the file to be saved by
        :py:meth:`render_and_save`.

        :param params: the :py:`ArchitypeParameter`s to use as context when
        building the content

        :return: the content of the file to be saved by
        :py:meth:`render_and_save`
        """
        raise NotImplementedError()

    def render_and_save(
            self,
            root_dir: str,
            params: ArchitypeParameters
    ) -> None:
        """
        Renders and saves the content of the file and saves it the
        appropriated directory under the root directory.  The content of the
        file as well as the subpath under the root directory may be,
        but need-not be, determined by the parameters argument.

        :param root_dir: the root directory under which the file should be
        saved

        :param params: the parameters used to determine the saved file
        content and possibly the subpath under the root directory

        :return: :py:const:`None`
        """
        raise NotImplementedError()


class BaseFileRenderer(FileRenderer):
    """
    This class provides default implementations of several of the methods in
    :py:class:`FileRender` whose results are derivable from the return
    values of other methods.  Subclasses need only provide implementations
    of :py:meth:`subpath` and :py:meth:`render`.
    """

    def path(self, root_dir: str, params: ArchitypeParameters) -> str:
        """
        Uses the implementation of :py:meth:`subpath` to determine the
        absolute path to the file saved by :py:meth:`render_and_save`.

        :param root_dir: the root directory argument for
        :py:meth:`render_and_save`

        :param params: the parameters argument for :py:meth:`render_and_save`

        :return: the path
        """
        return self._path(root_dir, params)

    @abstractmethod
    def subpath(self, params: ArchitypeParameters) -> str:
        """
        Subclasses are required to implement this method.  Implementations
        of this method should return the subpath, under the root directory,
        of the file to be saved by :py:meth:`render_and_save`.

        :param params: the :py:`ArchitypeParameter`s to use as context when
        creating the subpath, e.g., when storing files whose sub-path might be
        determined by the package name.

        :return: the path
        """
        raise NotImplementedError()

    @abstractmethod
    def render(self, params: ArchitypeParameters) -> str:
        """
        Subclasses are required to implement this method.  Implementations
        of this method should return the content of the file to be saved by
        :py:meth:`render_and_save`.

        :param params: the :py:`ArchitypeParameter`s to use as context when
        building the content

        :return: the content of the file to be saved by
        :py:meth:`render_and_save`
        """
        raise NotImplementedError()

    def render_and_save(
            self,
            root_dir: str,
            params: ArchitypeParameters
    ) -> None:
        """
        Renders and saves the content generated by :py:meth:`render` to the
        location under `root_dir` determined by the result of :py:`subpath`.

        Note that this method has dependencies on the implementations of
        :py:meth:`render` and :py:meth:`subpath`.

        :param root_dir: the root directory under which the file should be
        saved

        :param params: the parameters used to determine the saved file
        content and possibly the subpath under the root directory

        :return: :py:const:`None`
        """
        content = self.render(params)

        p = self._path(root_dir, params)
        try:
            os.makedirs(os.path.dirname(p))
        except OSError as exc:
            if exc.errno != errno.EEXIST:
                raise

        with open(p, 'w') as f:
            f.write(content)

    def _path(self, root_dir, params):
        return os.path.join(root_dir, self.subpath(params))
